# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build "
  lane :beta do 

    gradle(
      task: "clean assemble",
      flavor: "prod",
      build_type: "Release"
    )

    # output_path = "./app/build/outputs/apk/debug/"
    # output_json_path = output_path + "output-metadata.json"
    # build_output = load_json(json_path: output_json_path)
    # elements = build_output["elements"][0]
    # apk_path = output_path + elements["outputFile"]

    # build_android_app is a built-in fastlane action.
    firebase_app_distribution(
      app: "1:302933003992:android:35198cfa44331aa3fa11ad",
      firebase_cli_token: "1//0ee0gmPmuZ7TPCgYIARAAGA4SNwF-L9IrK4BmBx7gIAXGCYhEV-YxQQoUsoFZoTr2d1brumGIsdbaa3BtpLr9-m_61t8BcRy3PaY",
      android_artifact_path: "../build/app/outputs/apk/prod/release/app-prod-release.apk",
      testers: "nxhung16102001@gmail.com , humghuy201280@gmail.com",
      # release_notes: "Lots of amazing new features to test out!"
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: "clean bundle",
      flavor:"prod",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV["STORE_FILE"],
        "android.injected.signing.store.password" => ENV["STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
      }
    )
    upload_to_play_store(
      package_name: "com.realust.app",
      aab: "../build/app/outputs/bundle/prodRelease/app-prod-release.aab",
      track: 'beta'
    )
  end
end
